URL_SERVICE = "https://a5a5ee86-1aaf-43e4-a44a-47cbb0086a1c.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
MAIN_KITS = "/api/v1/kits/"
